### ISSUE TITLE
Login/Logout/Signup support?

### ISSUE THREAD

**Issue by brunokc** [Siumauricio/nextui-dashboard-template#13]
It would be great to have support for login, logout and signup pages in this template that match its current design.

Have you given it any thought?

**Comment by julienmaffar** [comment]
I open [PR](https://github.com/Siumauricio/nextui-dashboard-template/pull/17) for login / register system for this template.

**Comment by Siumauricio** [comment]
Thank you @julienmaffar ! PR merged
