### ISSUE TITLE
Please to upgrade to NextUI V2

### ISSUE THREAD

**Issue by neelhabib** [Siumauricio/nextui-dashboard-template#4]
Hi I loved your dashboard. 

I know you are busy but would love if you upgrade it to NextUI v2 tailwind. Many developers are waiting.

Thanks.

**Comment by Siumauricio** [comment]
Hey, this week i will work on migrating this dashboard

**Comment by itsbapic** [comment]
Just for the record - you have another prospective developer awaiting this update! Very keen to use this template to help us build out. Please give any updates on things like setbacks @Siumauricio

**Comment by rockse** [comment]
@Siumauricio any update on this? Would love to use it

**Comment by Siumauricio** [comment]
Hey, today I will start working on the migration in this branch

https://github.com/Siumauricio/nextui-dashboard-template/tree/v2

**Comment by Siumauricio** [comment]
@rockse @itsbapic @neelhabib Migration done you can check here  https://[nextui-dashboard-template.vercel.app](https://nextui-dashboard-template.vercel.app/)/
