### ISSUE TITLE
Website not loading CSS

### ISSUE THREAD

**Issue by DevSymo** [Siumauricio/nextui-dashboard-template#6]
Website right after clone and install isnt loading any css

**To Reproduce**
1. pnpm install
2. pnpm dev
3. website loads but not css
**Expected behavior**

**Screenshots**
<img width="1512" alt="image" src="https://github.com/Siumauricio/nextui-dashboard-template/assets/118448408/af4f0ced-f2ec-41f6-8cdb-3f8e32ed520e">

**Desktop:**
 - OS: MacOS Ventura 13 (Has same issue on windows)
 - Browser: Safari

**Comment by DevSymo** [comment]
pnpm breaks the css. just run as documentation states: npm install, npm run dev

**Comment by qutek** [comment]
@DevSymo How'd you go with that?

i got the same issue

**Comment by qutek** [comment]
nvm, we need to setup the hoist pattern. it works well now

https://nextui.org/docs/guide/installation#hoisted-dependencies-setup

**Comment by AafaqNamazi** [comment]
What's the hoisting pattern for NextUI? Since it has been changed to HeroUI, I'm still using NextUI.

**Comment by qutek** [comment]
@AafaqNamazi it should be `public-hoist-pattern[]=*@nextui-org/*`

**Comment by AafaqNamazi** [comment]
Thanks
